### ISSUE TITLE
Expand node options

### ISSUE THREAD

**Issue by WebSpider** [brotandgames/terraform-hcloud-rke#5]
**Is your feature request related to a problem? Please describe.**
Currently the options to pass to nodes being built are limited to the role. There are many more options that are interesting/useful to be able to pass

**Describe the solution you'd like**
Expand the nodes map to include:
hostname_override: maps to nodes.value.name (so that hostnames are present in Kubernetes, not node IPs)
labels: maps to new value nodes.value.labels, defaults to empty, so additional labels (for instance for scheduling) can be added
taints: maps to new value nodes.value.taints, defaults to empty, so taints (for instance for scheduling) can be added

**Describe alternatives you've considered**
Adding the labels/taints after creation using terraform, but the kubernetes provider doesnt support managing node objects

**Comment by brotandgames** [comment]
We are open for a PR concerning this feature.

We should implement an end to end test for this module. Any suggestions are welcome.

**Comment by brotandgames** [comment]
Closed as stale
